DROP TABLE IF EXISTS TX_REGISTER_TRANSACTION;

 create table TX_REGISTER_TRANSACTION(
    ID  BIGINT  IDENTITY(1,1)  PRIMARY KEY,
    TYPE_TRANSACTION VARCHAR(100),
    VALUE_TRANSACTION Decimal(30,2),
    TYPE_PERSON_ID VARCHAR(10),
    NUMBER_PERSON_ID decimal(20),
    NAMES_PERSON VARCHAR(50),
    LAST_NAME_PERSON varchar(50),
    DATE_CREATED DATETIME,
    USER_CREATED VARCHAR(50),
    DATE_LAST_MODIFY DATETIME,
    USER_LAST_MODIFY varchar(50)
);